"""empty message

Revision ID: e57ec7fd10b8
Revises: 
Create Date: 2021-02-22 11:12:22.899138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e57ec7fd10b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('image', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.Binary(), nullable=True),
    sa.Column('online', sa.Boolean(), nullable=False),
    sa.Column('image', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('friendship_offer',
    sa.Column('offered_to', sa.Integer(), nullable=True),
    sa.Column('offered_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['offered_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['offered_to'], ['user.id'], )
    )
    op.create_table('member_assoc',
    sa.Column('member', sa.Integer(), nullable=True),
    sa.Column('chat', sa.Integer(), nullable=True),
    sa.Column('owner', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['chat'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['member'], ['user.id'], )
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('member_assoc')
    op.drop_table('friendship_offer')
    op.drop_table('user')
    op.drop_table('chat')
    # ### end Alembic commands ###
